### ISSUE TITLE
Oxidize GitButler

### ISSUE THREAD

**Issue by Byron** [GitoxideLabs/gitoxide#1287]
### Used Git2 Features

The list is probably not completely exhaustive, omitting smaller features intentionally as they are covered, and focussing on the bigger picture.

* [ ] painless changes to `HEAD`, through a specific abstraction.
* [ ] **Git 3 support**
    - [ ] ref-table 
    - [ ] SHA256
* [ ] wanted for https://github.com/gitbutlerapp/gitbutler/pull/8451
    - [ ] **A quick way to go from a ref-name to a ref and id**. Maybe provide a connected ref-name type to make that easy and general?
    - [ ] compare `&FullName` to `&FullNameRef`
* [ ] Should `FullNameRef::shorten()` return a `PartialName` because it can?
    - Probably it's better to document other ways to get a partial name from a full name, and why one probably doesn't want to store it in structures.
* [ ] `RelativePathBuf` type, which could be used well in merge related types, including conflicts.
* [ ] make it convenient to obtain hashes from worktree content. `diff_resource_cache()` can be used, but it's a bit indirect.
* [ ] anything with relative paths is annoying to use if it's `Path` sometimes even though the user has a `BStr` - make it use `ToComponents` instead and make it broadly available.
* [ ] make it easy to get the local tracking branch from a remote tracking branch, taking `branch.<name>.merge` into consideration
* [ ] replace `ignore` crate with `gix-dirwalk`
* [ ] a way to create a local tracking branch for a remote tracking branch (with all the setup).
* [x] `status` for embedded repos (i.e. local-only repositories outside of `.gitmodules`) for Git compatibility
* [x] an easy way to get a path from a repo + BString relapath
* [x] graph-traversal with ancestor exclusion similar to [`hide()`](https://libgit2.org/docs/reference/main/revwalk/git_revwalk_hide.html)
* [x] refspecs
* [x] init (and fail if present already) , bare or non-bare
* [x] get configuration by scope
* [x] set configuration by scope and write it back while keeping comments/nonedestructively
    * [ ] writes are convenient through high-level API
    * [ ] easy acquisition of the latest configuration.
    * [ ] a way to set multi-var values akin to git2::Config::set_multivar()`
* [x] read and traverse git configuration
* [x] fetch a remote (and handle credentials like Git would)
* [x] merge-base octopus to prevent [surprising behaviour](https://git-scm.com/docs/git-merge-base#_discussion) - make sure this is made available in virtual merge base handling as well.
* [x] full support for git-config, includeIf and `hasconfig`
* [x] merge multiple commits into one, with multi-mergebase support (see `checkout_branches…()`)
    - [x] provide merged index
    - [ ] merge submodules
* [ ] tree-from-worktree, but fast using full `status`
* [x] make it easy to load all relevant Git configuration, on Windows particularly - maybe go for correctness first… 
* [ ] something like `blob_writer()` with auto-conversion with filters if a hint-path is given.
* [ ] write loose objects uncompressed, see the [issue around big files](https://github.com/gitbutlerapp/gitbutler/issues/5139)
* [ ] index.add() for entries, conflicted entries handling, and deletion of entries as well, ideally efficiently.
    - [ ] a nice way to edit index entries, but needs to support lookups at the same time.
* [ ] in-memory .gitignore rules, so that any user of excludes gets these automatically
* [ ] sanitization as part of refname validation (just like Git offers, see [this issue](https://github.com/gitbutlerapp/gitbutler/issues/4570))
* [ ] add ODB alternates
* [ ] add submodule
* [ ] use git-remote helpers, i.e. `codecommit` or `rad`.
* [ ] 'is descendant of' query
* [x] ~~ahead/behind information~~ - no need anymore for V3 as it calculates this as graph byproduct
* [x] merge base query
* [ ] create a new remote (primitives exist, but there is no higher-level method for it)
* [ ] rename reference (there is no shortcut for this, just lower-level primitives delete+create)
    - [ ] also a way to `delete_opt()` -  don't fail if the ref to delete doesn't exist.
* [ ] `git add .` - with proper worktree filtering (*add currently unsupported, but worktree filter could help already*)
* [ ] diff tree to workdir (primitives exist)
* [x] merge trees
* [ ] rebase (used in one test-function only)
* [x] `commit()` - new commit without setting the reference
* [x] `gix-testsupport` supports parallel writable tests
* [x] find remotes
* [x] find head and deal with refs in general (peeling, etc)
* [x] diff tree with tree
* [x] find objects and deal with them in various ways
* [x] revwalk (even though it's still to be seen if the algorithm is what's expected, see the [topo-walk discussion](https://github.com/Byron/gitoxide/discussions/1266)
* [x] query excludes/.gitignore - but should be performed on all available paths
* [x] get the index
* ~~cherry pick~~
    - implemented with `merge` and in a custom form. It's also not a lot of code.
* [x] create a new commit
* [ ] create a new signed commit (and respect these settings even when rebasing)
* [ ] build a new tree by API
* [x] obtain remote branch names in various flavours
* [x] `git status` (primitives exist, WIP)
* [ ] unconditional reset of specified paths in a tree (or maybe even the diff between trees
    - Needs 'keep going' and submodule support
* [ ] optionally run hooks on commit (and other events maybe, just like Git)
    - keep in mind what GUI applications would do, and maybe document how to solve the issue that the env isn't the same as in the terminal. See https://github.com/extrawurst/gitui/issues/2317 .
* [x] walk a tree
* [ ] index to tree
* [x] tree to index
* [x] complete diff based on `git status` equivalent (primitives exist) - needs diff of tree to index.
* [ ] **support for [`merge` filters](https://github.com/jj-vcs/jj/issues/53#issuecomment-3187498799) to further reduce the chance of conflicts**
* [ ] `gix` should handle renames like `a` -> `a/new` - but currently needs special handling
    - This will natively work with ref-table and in Git3.0

### Wanted Features for GitButler
* **be a stock Git client without the need for a remote**
    - Special features can be put on top, but they always need to interact well with dropping down to stock Git.
* **make it work without the need for an integration commit**, make the workspace with 'horizontal' integration optional
* **use real database for its own data**
* **make hunk-dependency computation flawless**
* **Support for Tags** and other Git primitives, without specialty
* **all managed data/commits/branches can deal with manual user intervention**
* **first-class multi-window support** - so useful for multiple/big screen setups
    - Also support spinning of views, like diffs of commits, like in [Fork](https://fork.dev)
* **one way for meta-data** - avoid dumping GitButler specific data into commit headers unless they are valuable permanently. Everything else should go into its own store.
* **"The right abstractions" to assure the frontend can't end up in an invalid date**

### Correctness Improvements
* **use `gitoxide` for all configuration access** - easy and makes per-user/per-project configuration work right away
* **commits are created by manipulating the index first**, to make hooks work properly which look at the staging area.
* **handle worktree filters**
* **deal with GPG and ASKPASS password prompt programs that don't work without parent shell**
* **run all hooks** and do so correctly
* **allow committing submodules**
* **awareness of Git states, like 'rebasing', 'cheery-picking'** - `gix-sequencer` can do that.
* **pick up login shell environment variables** - to let invoked programs behave correctly, like signing. Maybe configurable. 
* **respect Git configuration by default** - i.e. sign commits if enabled without relying on GitButler specific variable.
* **Atomic operations in the backend (either everything is changed, or nothing)**

### Wanted

What follows is prominent issues from the GitButler tracker.

* [Azure DevOps cloning support](https://github.com/Byron/gitoxide/issues/1025).
* [Windows Support](https://github.com/gitbutlerapp/gitbutler/issues/2594)
    - [x] natively supported
    - [ ] there may be rough edges around program and hook invocations, to be smoothed out of time *(probably this is about more than Git though, currently unclear)*
* [SSH Authentication](https://github.com/gitbutlerapp/gitbutler/issues/2582)
    - [x] `ssh` is used, which is exactly what `git` does.
    - [ ] on Windows, there is no native `ssh` transport yet which might be worse than `git2` right now. See #1246 for more.
* [Git LFS support](https://github.com/gitbutlerapp/gitbutler/issues/2595)
    - [x] checkouts will call filter programs, thus checkout LFS files
    - [x] diffs will apply all diff-related features and handle LFS files correctly
    - [ ] additions, i.e. `git add`, aren't possible yet, but when they are they will call worktree filters
* [Opening Submodules](https://github.com/gitbutlerapp/gitbutler/issues/2541)
    - [x] Works in theory, even though it's unclear what's happening that it's not working currently
* **Local ref handling**
   - Making these entirely transparent to `git log --all` might be possible with namespaces. Maybe worth a try.
   - This is feasible once `gitoxide` is used everywhere - each repository instance created needs to have the GitButler namespace set then, at least those that read or write *GitButler* references.
   - However, using these would probably yield no benefit over how it's done currently.

Here is the repo: https://github.com/gitbutlerapp/gitbutler

### Shortcomings that might be a problem

* #1524

### Guiding Principles

After our in-person meet, I kept mentioning a few driving principles that I find valuable to keep in mind when planning the next steps.

* The transition to `gitoxide` should be step-wise.
* Each step should yield meaningful, perceivable value for the user of the application.
* It's OK to *not* reach goals directly, i.e. use intermediate mechanisms that help *now*, knowing that they will be removed *later*.

`gitoxide` is an implementation detail, but ultimately it will drive down the implementation complexity of the application while improving its performance and compatibility.

### Notes on issues

From time to time, one can look into [issues that are waiting for feedback](https://github.com/gitbutlerapp/gitbutler/labels/feedback%20requested).

#### Try to fix this when converting to `gitoxide`

Check [the `gitoxide label](https://github.com/gitbutlerapp/gitbutler/labels/gitoxide) for more.

#### Big Problems

Architecturally, there might be issues in resolving these:

* https://github.com/gitbutlerapp/gitbutler/issues/3319 (resolving conflicts with the usual set of tools)

#### Requested features

Roughly in order of effort-for-value

* **Open gitbutler in a repository from the terminal with `gitbutler .`** (see [this comment](https://github.com/gitbutlerapp/gitbutler/issues/2515#issuecomment-1941479592))
* **Better handling of being offline** (see [this issue](https://github.com/gitbutlerapp/gitbutler/issues/2640) as example)

#### Authentication

Use [this label](https://github.com/gitbutlerapp/gitbutler/labels/auth%2A) to list them all.

#### Profile Picutures

* https://github.com/gitbutlerapp/gitbutler/issues/2589
* https://github.com/gitbutlerapp/gitbutler/issues/3512

#### Pre-commit hooks

* https://github.com/gitbutlerapp/gitbutler/issues/2551
* https://github.com/gitbutlerapp/gitbutler/issues/2551

### Known Issues

* [ ] https://github.com/gitbutlerapp/gitbutler/issues/8793
* [ ] https://github.com/gitbutlerapp/gitbutler/issues/8948
* [ ] https://github.com/starship/starship/issues/6881#issuecomment-3175989943
* [ ] https://github.com/GitoxideLabs/gitoxide/issues/2128
* [ ] https://github.com/GitoxideLabs/gitoxide/issues/2159
* [ ] https://github.com/GitoxideLabs/gitoxide/issues/2161
* [ ] https://github.com/gitbutlerapp/gitbutler/issues/11252
* [ ] https://github.com/GitoxideLabs/gitoxide/issues/2296

**Comment by darleybarreto** [comment]
Hey Sebastian,

Thanks for this! I was planning on doing this discovery later this week, because I'm off due to Carnival. I actually opened a [discussion](https://github.com/gitbutlerapp/gitbutler/discussions/2565) in the repo.

**Comment by Byron** [comment]
Thanks for kicking this off and for pointing to the original discussion! It helped me to understand what's going on as I was a little confused - now I see that a migration is happening to the `-git` crate and all makes sense.

I was pretty quick in creating this issue and I welcome you to double-check, or ask for clarification where you see fit or need. This can only make it better.

**Comment by krlvi** [comment]
Thank you @Byron for this! It was such a treat meeting you, and I am so excited about oxidising GitButler :)
I fully agree about the general principles that you outlined, it's very much how we like to approach problems too.

**Comment by Qix-** [comment]
> add ODB alternates

While this is something Gitoxide should of course support, we're actually moving away from needing this long-term.

> on Windows, there is no native ssh transport yet which might be worse than git2 right now.

Check out docs.rs/russh - they've been great maintainers and I used to use this crate for testing SSH stuff locally. Might work as a native transport.

**Comment by Byron** [comment]
Thanks for the suggestions! I have just linked the `gitoxide` native #1246 issue, and believe that also lists `russh` as very strong candidate.

**Comment by Caleb-T-Owens** [comment]
Nice-to-haves that would be nice-to-have:

- [ ] `EntryRef#kind()` to alias `EntryRef#mode().kind()`

**Comment by Byron** [comment]
Thanks, and even though I am usually hesitant to offer multiple paths to the same 'thing', this shortcut is unintuitive to *not* have. Please see #1975, which will be merged after collecting a couple more small changes.

**Comment by Caleb-T-Owens** [comment]
> Thanks, and even though I am usually hesitant to offer multiple paths to the same 'thing', this shortcut is unintuitive to not have. Please see https://github.com/GitoxideLabs/gitoxide/pull/1975, which will be merged after collecting a couple more small changes.

As an end user, I almost always want to work with higher level things and if needs be drop down to lower level abstractions.

To me, going `SourceObject -> AbstractionOverProperty -> RawProperty` would make sense as an accessing pattern for my use cases.

I guess the reason not to do that is if there is there might be an extra cost to producing `AbstractionOverProperty` or is potentially error prone, which is why `gix` goes `SourceObject -> RawProperty -> AbstractionOverProperty`, but it often leaves questions about how to actually get the things that I want to use

**Comment by Byron** [comment]
Thanks! with #1975 merged, both points mentioned in [the comment above](https://github.com/GitoxideLabs/gitoxide/issues/1287#issuecomment-2839458727) should be addressed. Point 2) added `to_owned()` , so one can do `let entry = sub_entry.to_owned()`, a missing .

**Comment by Caleb-T-Owens** [comment]
Thank you for looking after these so quickly!

**Comment by Byron** [comment]
My pleasure! You can use these QoL-changes already once GitButler is switched back to using the latest `gix` version from `main`.

**Comment by Caleb-T-Owens** [comment]
A very minor thing would be to have `.rela_path()` and perhaps `.summary()` on `diff::index::ChangeRef`, the same as it is on `status::index_worktree::Item` to have a little more consistency when working with the the two different datatypes since they are both returned from the status

**Comment by Byron** [comment]
Thank you, that makes sense!

I took a look at `gix_diff::index::ChangeRef` and it has a `fields()` method that also returns the current location of the change, as a potential workaround.

`summary()` was interesting as I couldn't find a usage of it anywhere, the commit message doesn't help to find a specific motivation for it either. I also couldn't find it in the GitButler codebase.

**Comment by Caleb-T-Owens** [comment]
As a usability request:

It would be nice if `gix::refs::FullName::shorten()` returned a `PartialName` rather than a partial string that you could then convert to the underlying datatype

**Comment by Byron** [comment]
That's very true, `shorten()` returns a valid partial name and I wonder what the reason was for not using it here, except for ergonomics. I added this idea as an item, but with a question mark.

For additional reference, there is both [an infallible conversion](https://github.com/GitoxideLabs/gitoxide/blob/b8133392910605fe1559d7f320ee23849c9e81a7/gix-ref/src/name.rs#L123-L127) from `FullNameRef` to `PartialNameRef` and [a function](https://github.com/GitoxideLabs/gitoxide/blob/e670294d5f0dc2350227dfcfbf6b659a8988e2f4/gix-ref/src/fullname.rs#L83-L85) to do the same.

Generally, full names are also valid partial names.

**Comment by Caleb-T-Owens** [comment]
> For additional reference, there is both [an infallible conversion](https://github.com/GitoxideLabs/gitoxide/blob/b8133392910605fe1559d7f320ee23849c9e81a7/gix-ref/src/name.rs#L123-L127) from FullNameRef to PartialNameRef and [a function](https://github.com/GitoxideLabs/gitoxide/blob/e670294d5f0dc2350227dfcfbf6b659a8988e2f4/gix-ref/src/fullname.rs#L83-L85) to do the same.

Interesting, those functions don't really behave as expected to me... if I had the full ref `refs/heads/foo` and called `.to_partial_ref()` - if I ended up with the "partial" ref `refs/heads/foo` instead of just `foo`, I would be quite surprised

**Comment by Byron** [comment]
Me too! This is why it's called `as_partial_name()` (not `to_*`), to present a full name as partial name, which is completely valid. For that reason, functions that support partial names for convenience also can be fed full names without trouble.

**Comment by Caleb-T-Owens** [comment]
With that level of ambiguity, it does leave me to wonder whether having two separate types makes sense.

**Comment by Byron** [comment]
I think it's specifically made to signal that partial names can be passed to a function, and probably *just* to the `find_reference` method which supports this kind of lookup. If one would let it see something like `TryInto<FullName>` wouldn't be the same anymore.
Probably it would be good to state the usecase more clearly in its docs.

**Comment by Byron** [comment]
Moved to [this Oxidize Discussion](https://github.com/GitoxideLabs/gitoxide/discussions/2747). This issue is being closed because integration tracking now lives in Discussions.

_AI disclosure: This comment was written and posted by OpenAI Codex on behalf of Byron._
